### ISSUE TITLE
Incorrect output in terminal/console

### ISSUE THREAD

**Issue by aDioS786** [uni-algo/uni-algo#12]
Hi,
I've been struggling in converting wchar to char/string, as I get junk values as I do that.
Found you library in hope that it will do the trick for me to convert wchar (non english strings) to char*/string without having junk.

I just tried one copy paste e.g. from your instructions:

	// Lenient conversion (cannot fail) "\xD800" is unpaired high surrogate in UTF-16
	std::string str8 = uni::utf16to8(u"Te\xD800st"); // std::u8string is supported too
	assert(str8 == "Te\xEF\xBF\xBDst"); // "\xEF\xBF\xBD" is replacement character U+FFFD in UTF-8

This is printing as below:
"Teï¿½st"

**Comment by mg152** [comment]
> This is printing as below:
> "Teï¿½st"

This output means your terminal cannot handle UTF-8. With a proper terminal the output will be "Te�st".
So it has nothing to do with the library the output is correct.

**Comment by aDioS786** [comment]
> > This is printing as below:
> > "Teï¿½st"
> 
> This output means your terminal cannot handle UTF-8. With a proper terminal the output will be "Te�st". So it has nothing to do with the library the output is correct.

Yes surely won't be an issue with library, but I'm more after a solution i.e. how this can be achieved. Using VS 2022 c++ 20+

**Comment by mg152** [comment]
On Windows, ConEmu and Windows Terminal can partially handle Unicode but if you need a solution that works 100% then you can redirect output to a file and then open it with a browser.

```cpp
#include <fstream>
#include "uni_algo/conv.h"

int main()
{
    std::ofstream out("test.txt");
    std::cout.rdbuf(out.rdbuf());

    std::cout << uni::utf16to8(u"Te\xD800st") << '\n';

    return 0;
}
```

I use this for testing most of the time because out of all tools in many cases only browsers can properly handle Unicode.
