### ISSUE TITLE
Functions for char32_t

### ISSUE THREAD

**Issue by igormironchik** [uni-algo/uni-algo#29]
I see you have case functions for UTF-8 and UTF-16, but why don't for UTF-32?

**Comment by mg152** [comment]
UTF-32 strings are not widely used, so no point to implement functions that work with them.

**Comment by igormironchik** [comment]
Concider I have an UTF-8 string, with your view I can iterate over each symbol. OK, but what if I want to do case folding for each of this symbol, how can I do it?

```cpp
std::string str8 = "😺😼🙀";
auto view = una::ranges::utf8_view{str8};

for (auto it = view.begin(); it != view.end(); ++it)
{
    const auto caseFolded = ???( *it ); // ??? - HOW???
}
```

**Comment by mg152** [comment]
Case folding/lowercase/uppercase views are not implemented at the moment. They are planned and will be implemented the same as normalization views.

Right now you can do it manually through properties `uni_algo/prop.h` like this:
```cpp
std::string str8 = "Straße";
auto view = una::ranges::utf8_view{str8};

for (auto it = view.begin(); it != view.end(); ++it)
{
    std::u32string s = una::codepoint::to_casefold_u32(*it); // Full case folding
    char32_t c = una::codepoint::to_simple_casefold(*it); // Simple case folding
}
```
