### ISSUE TITLE
Plans for version 1.0

### ISSUE THREAD

**Issue by mg152** [uni-algo/uni-algo#3]
- [x] Stable API (I'll make a post about this later to see what people don't like in API)
- [x] Switch from iterators to ranges
- [x] Add support for `char8_t` strings
- [x] Code point properties and ability for existing modules to expose properties they use
- [x] Better locale class
- [x] Add reverse algorithms to grapheme/word ranges
- [x] Add cursor support to grapheme/word ranges
- [x] Add word properties
- [x] Ability to use custom allocators for all functions that allocate
- [x] Add UTF validation functions
- [x] Use `std::string.resize_and_overwrite` instead of `std::string.resize` in C++23
- [x] UAX 24: Unicode Script Property
- [ ] UAX 14: Unicode Line Breaking Algorithm (might be postponed after v1.0.0)
- [ ] UAX 9: Unicode Bidirectional Algorithm (might be postponed after v1.0.0)
- [x] Add safe layer
- [x] Add header-only version
- [x] Make everything constexpr
- [x] Reduce Unicode data size and more performance optimizations
- [ ] C++20 Modules if support in compilers will be good enough

**Comment by data-man** [comment]
Just recently found your project, thank you very much!

What about adding the `width` property and calculating the string width?

**Comment by mg152** [comment]
`width` is kind of awkward property in Unicode. I need to investigate first how to handle it properly, so it won't be in version 1.0 for sure.

**Comment by ameisen** [comment]
Any chance you might introduce converter functions that return `std::array`s instead, perhaps taking `std::array`, `const T(&)[N]`, or such?

This would make compile-time conversion and static storage easier since the `std::basic_string` allocation could be avoided

**Comment by mg152** [comment]
Version 1.0.0 has been released.
