### ISSUE TITLE
"L with stroke" unnacent function fails

### ISSUE THREAD

**Issue by Emaer1916** [uni-algo/uni-algo#31]
Hi. L with stroke letter (U+0141, U+0142) doesn't normalize.
```cpp
auto const polish = std::string{"ąćęłńóśźż ĄĆĘŁŃÓŚŹŻ"};
auto norm = una::norm::to_unaccent_utf8(polish);
```
Everything is normalized except 'ł' and 'Ł'.

Did I miss something?

**Comment by mg152** [comment]
Strokes are not accents. As far as I know there is no data table in Unicode that maps L with stroke to L so no plans to implemented it, you need to do it manually if needed.

**Comment by Emaer1916** [comment]
I was a bit rushed with this question.
I have read more about it and indeed 'Ł'/'ł' requires individual treatment.
Thanks!
